/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

import Controlador.Controlador;

/**
 *
 * @author SOFIA ELIZONDO
 */
public class InformacionCita extends javax.swing.JFrame {

    /**
     * Creates new form InformacionCita
     */
    Controlador controlador;
    public InformacionCita(Controlador controlador) {
        initComponents();
        this.controlador=controlador;
        setLocation(400,200);
        setVisible(false);
        agregarEventos();
        desabilitarEdicion();
    }
    
    public int enviarInformacionEdad()
    {
        int datos=0;
        datos=Integer.parseInt(jt_Edad.getText());
        return datos;
    }
    
    public String[] enviarInformacion()
    {
        String[] datos=new String[3];
        datos[1]=jt_Nombre.getText();
        datos[0]=this.jt_Cedula.getText();
        datos[2]=jt_Cita.getText();
        return datos;
    }
    
    public void refresarVentana()
    {
        this.jt_Cedula.setText("");
        this.jt_Nombre.setText("");
        this.jt_Edad.setText("");
    }
    
    public void habilitarEdicion()
    {
        this.jt_Cedula.setEnabled(false);
        this.jt_Cita.setEnabled(true);
        this.jt_Edad.setEnabled(true);
        this.jt_Nombre.setEnabled(true);
        this.btn_Eliminar.setEnabled(true);
        this.btn_Modificar.setEnabled(true);
        this.btn_Buscar.setEnabled(false);
    }
    
    public void desabilitarEdicion()
    {
        this.jt_Cedula.setEnabled(true);
        this.jt_Cita.setEnabled(false);
        this.jt_Edad.setEnabled(false);
        this.jt_Nombre.setEnabled(false);
        this.btn_Eliminar.setEnabled(false);
        this.btn_Modificar.setEnabled(false);
        this.btn_Buscar.setEnabled(true);
    }
    public void agregarEventos()
    {
        this.btn_Buscar.addActionListener(controlador);
        this.btn_Eliminar.addActionListener(controlador);
        this.btn_Modificar.addActionListener(controlador); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jl_Titulo = new javax.swing.JLabel();
        jl_Nombre = new javax.swing.JLabel();
        jl_Cedula = new javax.swing.JLabel();
        jl_Edad = new javax.swing.JLabel();
        jt_Cedula = new javax.swing.JTextField();
        jt_Nombre = new javax.swing.JTextField();
        jt_Edad = new javax.swing.JTextField();
        jl_TituloFicha = new javax.swing.JLabel();
        jt_Cita = new javax.swing.JTextField();
        btn_Buscar = new javax.swing.JButton();
        btn_Modificar = new javax.swing.JButton();
        btn_Eliminar = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        jButton1.setText("jButton1");

        setMinimumSize(new java.awt.Dimension(300, 350));
        setPreferredSize(new java.awt.Dimension(300, 350));

        jl_Titulo.setText("Información Cita");

        jl_Nombre.setText("Nombre");

        jl_Cedula.setText("Cédula");

        jl_Edad.setText("Edad");

        jl_TituloFicha.setText("Fecha");
        jl_TituloFicha.setToolTipText("");

        jt_Cita.setText("dd/mm/0000");
        jt_Cita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_CitaActionPerformed(evt);
            }
        });

        btn_Buscar.setText("Buscar");
        btn_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BuscarActionPerformed(evt);
            }
        });

        btn_Modificar.setText("Modificar");

        btn_Eliminar.setText("Eliminar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jl_Titulo)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jl_Edad)
                                    .addComponent(jl_TituloFicha))
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jt_Cita, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                                    .addComponent(jt_Edad)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jl_Nombre)
                                        .addGap(41, 41, 41)
                                        .addComponent(jt_Nombre))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jl_Cedula)
                                        .addGap(45, 45, 45)
                                        .addComponent(jt_Cedula)))
                                .addGap(18, 18, 18)
                                .addComponent(btn_Buscar))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(btn_Modificar)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Eliminar)))
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jl_Titulo)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jl_Cedula))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jt_Cedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_Buscar)))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jl_Nombre))
                    .addComponent(jt_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jl_Edad))
                    .addComponent(jt_Edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jl_TituloFicha)
                    .addComponent(jt_Cita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Modificar)
                    .addComponent(btn_Eliminar))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_BuscarActionPerformed

    private void jt_CitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_CitaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_CitaActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Buscar;
    private javax.swing.JButton btn_Eliminar;
    private javax.swing.JButton btn_Modificar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jl_Cedula;
    private javax.swing.JLabel jl_Edad;
    private javax.swing.JLabel jl_Nombre;
    private javax.swing.JLabel jl_Titulo;
    private javax.swing.JLabel jl_TituloFicha;
    private javax.swing.JTextField jt_Cedula;
    private javax.swing.JTextField jt_Cita;
    private javax.swing.JTextField jt_Edad;
    private javax.swing.JTextField jt_Nombre;
    // End of variables declaration//GEN-END:variables
}
